### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by Lucifer1002** [Delay-Xili/F-Clip#20]
What is the reason for the following error message during training?

Traceback (most recent call last):
  File "train.py", line 207, in <module>
    main()
  File "train.py", line 197, in main
    trainer.train()
  File "D:\Code\F-Clip-master\FClip\trainer.py", line 218, in train
    self.train_epoch()
  File "D:\Code\F-Clip-master\FClip\trainer.py", line 169, in train_epoch
    for batch_idx, (image, meta, target) in enumerate(self.train_loader):
  File "C:\Users\15146\anaconda3\envs\f-clip\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "C:\Users\15146\anaconda3\envs\f-clip\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "C:\Users\15146\anaconda3\envs\f-clip\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "C:\Users\15146\anaconda3\envs\f-clip\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FClip.box.BoxKeyError: 'Caught BoxKeyError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "D:\\Code\\F-Clip-master\\FClip\\box.py", line 412, in __getitem__\n    value = super(Box, self).__getitem__(item)\nKeyError: \'stage1\'\n\nDuring handling of the above exception, 
another exception occurred:\n\nTraceback (most recent call last):\n  File "D:\\Code\\F-Clip-master\\FClip\\box.py", line 492, in __getattr__\n    value = self.__getitem__(item, _ignore_default=True)\n  File "D:\\Code\\F-Clip-master\\FClip\\box.py", line 419, in __getitem__\n    raise BoxKeyError(str(err))\n
FClip.box.BoxKeyError: "\'stage1\'"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "D:\\Code\\F-Clip-master\\FClip\\box.py", line 494, in __getattr__\n    value = object.__getattribute__(self, item)\nAttributeError: \'Box\' object has no 
attribute \'stage1\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "C:\\Users\\15146\\anaconda3\\envs\\f-clip\\lib\\site-packages\\torch\\utils\\data\\_utils\\worker.py", line 198, in _worker_loop\n    data = fetcher.fetch(index)\n  File
 "C:\\Users\\15146\\anaconda3\\envs\\f-clip\\lib\\site-packages\\torch\\utils\\data\\_utils\\fetch.py", line 44, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File "C:\\Users\\15146\\anaconda3\\envs\\f-clip\\lib\\site-packages\\torch\\utils\\data\\_utils\\fetch.py", line 44, 
in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n  File "D:\\Code\\F-Clip-master\\FClip\\datasets.py", line 54, in __getitem__\n    if M.stage1 == "fclip":\n  File "D:\\Code\\F-Clip-master\\FClip\\box.py", line 511, in __getattr__\n    raise BoxKeyError(str(err))\nFClip.box.BoxKeyError: "\'Box\' object has no attribute \'stage1\'"\n'

**Comment by yajin-xu** [comment]
I believe it is due to a missing configuration variable. Check your config file and look for "stage1" to see if it got deleted by accident.

Also, are you trying to train with your own dataset? If yes, could you let me know about the final performance when you are done? Thanks!

**Comment by Akj170245** [comment]
I am also facing the same error. I have modified the .yaml file with stage1 parameter in the model section. but still facing the same error. Please give any suggestions to resolve this issue. I am training it on my own dataset.

Traceback (most recent call last):
  File "/Users/ankurkumarjaiswal/Downloads/F-Clip/train.py", line 227, in <module>
    main()
  File "/Users/ankurkumarjaiswal/Downloads/F-Clip/train.py", line 136, in main
    for batch_idx, (images, meta, targets) in enumerate(train_loader):
  File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
FClip.box.BoxKeyError: 'Caught BoxKeyError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 412, in __getitem__\n    value = super(Box, self).__getitem__(item)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyError: \'stage1\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 492, in __getattr__\n    value = self.__getitem__(item, _ignore_default=True)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 419, in __getitem__\n    raise BoxKeyError(str(err))\nFClip.box.BoxKeyError: "\'stage1\'"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 494, in __getattr__\n    value = object.__getattribute__(self, item)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: \'Box\' object has no attribute \'stage1\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop\n    data = fetcher.fetch(index)\n           ^^^^^^^^^^^^^^^^^^^^\n  File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>\n    data = [self.dataset[idx] for idx in possibly_batched_index]\n            ~~~~~~~~~~~~^^^^^\n  File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/datasets.py", line 58, in __getitem__\n    if M.stage1 == "fclip":\n       ^^^^^^^^\n  File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 511, in __getattr__\n    raise BoxKeyError(str(err))\nFClip.box.BoxKeyError: "\'Box\' object has no attribute \'stage1\'"\n'

**Comment by HonestyBrave** [comment]
@Akj170245 hi，i have meet the same problem, do you have handle it?
