### ISSUE TITLE
Training on custom dataset?

### ISSUE THREAD

**Issue by yajin-xu** [Delay-Xili/F-Clip#21]
Hello to all,

Has anyone tried training with their own datasets? I tried with mine, but the result is much worse than L-CNN... It would be nice if someone could have a discussion and help me identify the problem. Thanks!

Cheers

**Comment by Akj170245** [comment]
> Hello to all,
> 
> Has anyone tried training with their own datasets? I tried with mine, but the result is much worse than L-CNN... It would be nice if someone could have a discussion and help me identify the problem. Thanks!
> 
> Cheers

can you please tell how to resolve this issue ??
I have modified the .yaml file with stage1 parameter in the model section. but still facing the same error. Please give any suggestions to resolve this issue. I am training it on my own dataset.

Traceback (most recent call last):
File "/Users/ankurkumarjaiswal/Downloads/F-Clip/train.py", line 227, in
main()
File "/Users/ankurkumarjaiswal/Downloads/F-Clip/train.py", line 136, in main
for batch_idx, (images, meta, targets) in enumerate(train_loader):
File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in next
data = self._next_data()
^^^^^^^^^^^^^^^^^
File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
return self._process_data(data)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
data.reraise()
File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
raise exception
FClip.box.BoxKeyError: 'Caught BoxKeyError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 412, in getitem\n value = super(Box, self).getitem(item)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyError: 'stage1'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 492, in getattr\n value = self.getitem(item, _ignore_default=True)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 419, in getitem\n raise BoxKeyError(str(err))\nFClip.box.BoxKeyError: "'stage1'"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 494, in getattr\n value = object.getattribute(self, item)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Box' object has no attribute 'stage1'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop\n data = fetcher.fetch(index)\n ^^^^^^^^^^^^^^^^^^^^\n File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch\n data = [self.dataset[idx] for idx in possibly_batched_index]\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in \n data = [self.dataset[idx] for idx in possibly_batched_index]\n ~~~~~~~~~~~~^^^^^\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/datasets.py", line 58, in getitem\n if M.stage1 == "fclip":\n ^^^^^^^^\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 511, in getattr\n raise BoxKeyError(str(err))\nFClip.box.BoxKeyError: "'Box' object has no attribute 'stage1'"\n'

**Comment by yajin-xu** [comment]
> > Hello to all,
> > Has anyone tried training with their own datasets? I tried with mine, but the result is much worse than L-CNN... It would be nice if someone could have a discussion and help me identify the problem. Thanks!
> > Cheers
> 
> can you please tell how to resolve this issue ?? I have modified the .yaml file with stage1 parameter in the model section. but still facing the same error. Please give any suggestions to resolve this issue. I am training it on my own dataset.
> 
> Traceback (most recent call last): File "/Users/ankurkumarjaiswal/Downloads/F-Clip/train.py", line 227, in main() File "/Users/ankurkumarjaiswal/Downloads/F-Clip/train.py", line 136, in main for batch_idx, (images, meta, targets) in enumerate(train_loader): File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in next data = self._next_data() ^^^^^^^^^^^^^^^^^ File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data return self._process_data(data) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data data.reraise() File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise raise exception FClip.box.BoxKeyError: 'Caught BoxKeyError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 412, in getitem\n value = super(Box, self).getitem(item)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nKeyError: 'stage1'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 492, in getattr\n value = self.getitem(item, _ignore_default=True)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 419, in getitem\n raise BoxKeyError(str(err))\nFClip.box.BoxKeyError: "'stage1'"\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 494, in getattr\n value = object.getattribute(self, item)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Box' object has no attribute 'stage1'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop\n data = fetcher.fetch(index)\n ^^^^^^^^^^^^^^^^^^^^\n File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch\n data = [self.dataset[idx] for idx in possibly_batched_index]\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/Users/ankurkumarjaiswal/miniconda3/envs/fclip/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in \n data = [self.dataset[idx] for idx in possibly_batched_index]\n ~~~~~~~~~~~~^^^^^\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/datasets.py", line 58, in getitem\n if M.stage1 == "fclip":\n ^^^^^^^^\n File "/Users/ankurkumarjaiswal/Downloads/F-Clip/FClip/box.py", line 511, in getattr\n raise BoxKeyError(str(err))\nFClip.box.BoxKeyError: "'Box' object has no attribute 'stage1'"\n'

The stage1 parameter should be stored under model, in your yaml file something structured like
```
model:
  stage1: XXX
```
