### ISSUE TITLE
模型文件不对

### ISSUE THREAD

**Issue by HonestyBrave** [Delay-Xili/F-Clip#23]
博主你好，非常感谢你分享了代码和模型。关于模型这一块我有点疑问，就是我按照你给的谷歌地址下载了模型，解压后如下图所示，在里面没有找到 .pth文件，不知道是不是我哪里没弄好，还请博主指点下，万分感谢！

![image](https://github.com/user-attachments/assets/f8ddf469-4e72-4934-882f-e749a28bdac3)

运行：**python demo.py E:\temp\testimg --model HG1 --output_dir logs/demo_result --ckpt E:\temp\HG1-20241121T012122Z-001\HG1\archive\data.pkl --display True**
报如下问题：

(fclip) E:\github\F-Clip>python demo.py E:\temp\testimg --model HG1 --output_dir logs/demo_result --ckpt E:\temp\HG1-20241121T012122Z-001\HG1\archive\E:\temp\1\HG1-20241121T012122Z-001\HG1\checkpoint.pth\archive\data.pkl --display True
Namespace(input='E:\\temp\\testimg', model='HG1', output_dir='logs/demo_result', ckpt='E:\\temp\\HG1-20241121T012122Z-001\\HG1\\archive\\E:\\temp\\1\\HG1-20241121T012122Z-001\\HG1\\checkpoint.pth\\archive\\data.pkl', camid=0, img_glob='*.png', skip=1, waitkey=1, display=True)
logs/demo_result
==> Loading video.
[ WARN:0@2.969] global cap_gstreamer.cpp:2840 cv::handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not open file "E:\temp\testimg" for reading.
[ WARN:0@2.969] global cap_gstreamer.cpp:1698 cv::GStreamerCapture::open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@2.969] global cap_gstreamer.cpp:1173 cv::GStreamerCapture::isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@3.321] global loadsave.cpp:241 cv::findDecoder imread_('E:\temp\testimg'): can't open/read file: check file path/integrity
==> Processing Image Directory Input.
==> Successfully loaded video.
Using device:  cpu
0-th head, head type raw, head output 2
1-th head, head type raw, head output 2
2-th head, head type raw, head output 1
3-th head, head type raw, head output 1
E:\github\F-Clip\test.py:105: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(C.io.model_initialize_file, map_location=torch.device('cpu'))
Traceback (most recent call last):
  File "E:\github\F-Clip\demo.py", line 268, in <module>
    detector = FClipDetect(opt.model, opt.ckpt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\github\F-Clip\demo.py", line 207, in __init__
    self.model = build_model(cpu=iscpu)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\github\F-Clip\test.py", line 105, in build_model
    checkpoint = torch.load(C.io.model_initialize_file, map_location=torch.device('cpu'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\fclip\Lib\site-packages\torch\serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\fclip\Lib\site-packages\torch\serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\fclip\Lib\site-packages\torch\serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'E:\\temp\\HG1-20241121T012122Z-001\\HG1\\archive\\E:\\temp\\1\\HG1-20241121T012122Z-001\\HG1\\checkpoint.pth\\archive\\data.pkl'

运行：**python demo.py E:\temp\testimg --model HG1 --output_dir logs/demo_result --ckpt E:\temp\HG1-20241121T012122Z-001\HG1\archive --display True**

报如下问题：
(fclip) E:\github\F-Clip>python demo.py E:\temp\testimg --model HG1 --output_dir logs/demo_result --ckpt E:\temp\HG1-20241121T012122Z-001\HG1\archive --display True
Namespace(input='E:\\temp\\testimg', model='HG1', output_dir='logs/demo_result', ckpt='E:\\temp\\HG1-20241121T012122Z-001\\HG1\\archive', camid=0, img_glob='*.png', skip=1, waitkey=1, display=True)
logs/demo_result
==> Loading video.
[ WARN:0@2.248] global cap_gstreamer.cpp:2840 cv::handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not open file "E:\temp\testimg" for reading.
[ WARN:0@2.248] global cap_gstreamer.cpp:1698 cv::GStreamerCapture::open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@2.250] global cap_gstreamer.cpp:1173 cv::GStreamerCapture::isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0@2.671] global loadsave.cpp:241 cv::findDecoder imread_('E:\temp\testimg'): can't open/read file: check file path/integrity
==> Processing Image Directory Input.
==> Successfully loaded video.
Using device:  cpu
0-th head, head type raw, head output 2
1-th head, head type raw, head output 2
2-th head, head type raw, head output 1
3-th head, head type raw, head output 1
E:\github\F-Clip\test.py:105: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(C.io.model_initialize_file, map_location=torch.device('cpu'))
Traceback (most recent call last):
  File "E:\github\F-Clip\demo.py", line 268, in <module>
    detector = FClipDetect(opt.model, opt.ckpt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\github\F-Clip\demo.py", line 207, in __init__
    self.model = build_model(cpu=iscpu)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\github\F-Clip\test.py", line 105, in build_model
    checkpoint = torch.load(C.io.model_initialize_file, map_location=torch.device('cpu'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\fclip\Lib\site-packages\torch\serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\fclip\Lib\site-packages\torch\serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\miniconda3\envs\fclip\Lib\site-packages\torch\serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'E:\\temp\\HG1-20241121T012122Z-001\\HG1\\archive'

**Comment by WelcomeToWonderland** [comment]
你好，可以分享一下，你下载的模型权重文件吗？作者分享的谷歌网盘地址，现在好像进不去？
万分感谢！

**Comment by HonestyBrave** [comment]
> 你好，可以分享一下，你下载的模型权重文件吗？作者分享的谷歌网盘地址，现在好像进不去？ 万分感谢！

我是从作者放的谷歌盘上下载的，我怎么分享给你呢？
